version: '3.9'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:////data/app.db
      - BACKEND_CORS_ORIGINS=*
    volumes:
      - ./data:/data
